package com.openbravo.pos.reports;

import com.openbravo.data.loader.SerializerWrite;
import com.openbravo.pos.forms.AppView;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.util.List;
import com.openbravo.basic.BasicException;
import com.openbravo.data.gui.ComboBoxValModel;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.IKeyed;
import com.openbravo.data.loader.QBFCompareEnum;
import com.openbravo.data.loader.SentenceList;
import com.openbravo.data.loader.SerializerWriteBasic;
import com.openbravo.pos.forms.AppLocal;
class ComboItemLocal implements IKeyed {

    protected Integer m_iKey;
    protected String m_sKeyValue;

    public ComboItemLocal(Integer iKey, String sKeyValue) {
        m_iKey = iKey;
        m_sKeyValue = sKeyValue;
    }
    public Object getKey() {
        return m_iKey;
    }
    public Object getValue() {
        return m_sKeyValue;
    }
    public String toString() {
        return AppLocal.getIntString(m_sKeyValue);
    }
} 

public class JParamsPagos extends javax.swing.JPanel implements ReportEditorCreator {
    
    private ComboBoxValModel m_ReasonModel;
    private ComboBoxValModel m_LocationsModel;    
    /** Creates new form JParamsLocation */
    public JParamsPagos() {
        /*initComponents();   
        m_ReasonModel = new ComboBoxValModel();
        m_ReasonModel.add(new ComboItemLocal(1,"Deposito"));
        m_ReasonModel.add(new ComboItemLocal(2,"Tarjeta"));
        m_ReasonModel.add(new ComboItemLocal(3,"Efectivo"));
        m_ReasonModel.add(new ComboItemLocal(4,"Dev_Efectivo"));
        m_ReasonModel.add(new ComboItemLocal(5,"Dev_Deposito"));
        m_ReasonModel.add(new ComboItemLocal(6,"Deuda"));
        m_ReasonModel.add(new ComboItemLocal(7,"Pago_Deuda"));
        
        m_jLocation.setModel(m_ReasonModel);
        */
    }

    public void init(AppView app) {
         
        //DataLogicSales dlSales = (DataLogicSales) app.getBean("com.openbravo.pos.forms.DataLogicSales");
        //this.app = app;
        // El modelo de locales
        //m_sentlocations = dlSales.getLocationsList();
        //m_LocationsModel = new ComboBoxValModel();   
    }
        
    public void activate() throws BasicException {
        //List a = new ArrayList();
        //addFirst(a);
        /*
        m_LocationsModel = new ComboBoxValModel(a);
        if(!app.getInventoryLocation().equals("0"))
        {
            m_LocationsModel.setSelectedKey(app.getInventoryLocation());
            m_jLocation.setEnabled(false);
        }
        
        else m_LocationsModel.setSelectedFirst();*/
        //m_jLocation.setModel(m_ReasonModel);
    }
    
    public SerializerWrite getSerializerWrite() {
        return new SerializerWriteBasic(new Datas[] {Datas.OBJECT, Datas.STRING});
    }

    public Component getComponent() {
        return this;
    }

    
    protected void addFirst(List a) {
        // do nothing
    }
    
    public void addActionListener(ActionListener l) {
        //m_jLocation.addActionListener(l);
    }
    
    public void removeActionListener(ActionListener l) {
        //m_jLocation.removeActionListener(l);
    }
    
    public Object createValue() throws BasicException {
        /*String tipo="";
        if(m_jLocation.getSelectedItem().toString().equalsIgnoreCase("Deposito"))
            tipo="cheque";
        else if(m_jLocation.getSelectedItem().toString().equalsIgnoreCase("Efectivo"))
            tipo="cash";
        else if(m_jLocation.getSelectedItem().toString().equalsIgnoreCase("Dev_Efectivo"))
            tipo="cashrefund";
        else if(m_jLocation.getSelectedItem().toString().equalsIgnoreCase("Tarjeta"))
            tipo="magcard";
        else if(m_jLocation.getSelectedItem().toString().equalsIgnoreCase("Dev_Deposito"))
            tipo="chequerefund";
        else if(m_jLocation.getSelectedItem().toString().equalsIgnoreCase("Deuda"))
            tipo="debt";
        else if(m_jLocation.getSelectedItem().toString().equalsIgnoreCase("Pago_deuda"))
            tipo="debtpaid";*/
        return new Object[] {
            QBFCompareEnum.COMP_EQUALS, 
            ""
        };
    }    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_jLocation = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(AppLocal.getIntString("label.bywarehouse"))); // NOI18N

        jLabel8.setText("Pago");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_jLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(m_jLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox m_jLocation;
    // End of variables declaration//GEN-END:variables
    
}
